[features]
seeds = false
skip-lint = false
[programs.localnet]
mysolanaapp = "6hE81nLyVUfzqH9RWWuGKbkpXDbM5AA15dbEgTzZv4Yg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/waterbrosol/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
